spring:
  # JPA settings
  jpa:
    hibernate:
      ddl-auto: create # ? ??? ?????? ?? ??? ???? drop ??, ?? ????.
    properties:
      hibernate:
        format_sql: true # ??? 1?? ??? ????? ? ? ?? ?? ??? ??
#        show_sql: true # JPA? ???? SQL? ?? ?? ?? ???? ?? -> ??? log? ??? ?? ???? ?? ?? org.hibernate.sql: debug ??? ??.

  # H2 DB DataSource
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:

logging:
  level:
#    root: info

    # jpa hibernate? ???? sql? ??? ??? ???? ?? ??
    org.hibernate.sql: debug # hibernate? ??? ?? ??? debug??? ??
#    org.hibernate.type: trace # ?? ???? ???? ??? ???? ?? # Using the dependency(implementation 'com.github.gavlyukovskiy:p6spy-spring-boot-starter:1.5.7') is more convenient than 'org.hibernate.type: trace'